# Generated by Django 5.0.2 on 2024-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="post.postattachment"),
        ),
    ]
