# Generated by Django 5.0.2 on 2024-03-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="cerated_at",
            new_name="created_at",
        ),
    ]
