# Generated by Django 5.0.2 on 2024-03-15 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
