# Generated by Django 5.0.3 on 2024-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
    ]
